
[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[scrolling]
history = 100000

[font]
size = 13.0
[font.normal]

family = "MesloLGS Nerd Font"
style = 'Regular'

[font.offset]
x= 1
y = 1

[window]
padding = {x = 15, y= 10 }
decorations = "Buttonless"
opacity = 1


[keyboard]
bindings = [
{ key = "N", mods = "Command", action = "CreateNewWindow" }
]

[mouse]
hide_when_typing = true

[colors]
draw_bold_text_with_bright_colors = true

[general]
live_config_reload = true

import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[terminal]
