#!/usr/bin/env sh

# using bat to parse help
function bathelp() {
    
    if [[ $# > 0 ]]; then
       echo "Bad use of global --help alias detected! Please use \\--help instead, optionally adding | bathelp manually"
       return
    fi 

   bat --language=help --style=plain
}

alias -g -- -h='-h 2>&1 | bathelp'
alias -g -- --help='--help 2>&1 | bathelp'